### ISSUE TITLE
 TypeError: $(...).metisMenu is not a function

### ISSUE THREAD

**Issue by yasserzaid** [onokumus/metisMenu#120]
Dear,
I'm using Bootstrp with JQuery UI Calender DatePicker and i got this error i think there is a conflict 

Please how can i solve this issue

Thank you

**Comment by onokumus** [comment]
Hi @yasserzaid 
Could you give some more detail?

**Comment by yasserzaid** [comment]
I'm using ASP.Net application and use Bootstrap design with Menu and i have ASPX Page with JQuery UI Calendar (date-picker) when i open this page from Menu the collapse and expand of Menu is not working and for any other page not using JQuery Calendar Menu works fine

Kindly advice

**Comment by onokumus** [comment]
It should not be in conflict with jQuery UI. What are the error messages on the console?

**Comment by yasserzaid** [comment]
I got this message
- Warning Message 
jQuery.Deferred exception: $(...).metisMenu is not a function TypeError: $(...).metisMenu is not a function
    at HTMLDocument.<anonymous> (http://yasserzaid-001-site1.btempurl.com/Scripts/sb-admin-2.js:4:21)
    at mightThrow (http://yasserzaid-001-site1.btempurl.com/Scripts/jquery-3.1.1.js:3570:29)
    at process (http://yasserzaid-001-site1.btempurl.com/Scripts/jquery-3.1.1.js:3638:12) undefined
- Error Message 
Uncaught TypeError: $(...).metisMenu is not a function
    at HTMLDocument.<anonymous> (sb-admin-2.js:4)
    at mightThrow (jquery-3.1.1.js:3570)
    at process (jquery-3.1.1.js:3638)

Thank you.

**Comment by onokumus** [comment]
Could you try using jQuery version 3.1.1 or 2.2.4?

**Comment by yasserzaid** [comment]
Dear,
I did and not working too
i used 3.0.1 and 3.1.1 and 3.1.1.min and not working
I think this because jquery version conflict between js for bootstrap and UI calendar

Any advise

**Comment by epaulgrmx** [comment]
so... can you fix your problem?

**Comment by stillAnd** [comment]
now...I want to know,  have you solve this problem now?😂

**Comment by yasserzaid** [comment]
No not yet

**Comment by smhnkmr** [comment]
@onokumus I too have the same issue. any suggestions?

**Comment by stillAnd** [comment]
> @onokumus I too have the same issue. any suggestions?

No, you can choose to cancel use the bootstrap,-.->
